// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/AlexanderYukhanov/90minsGOexp/server/models"
)

// NewCreateAppointmentParams creates a new CreateAppointmentParams object
// no default values defined in spec.
func NewCreateAppointmentParams() CreateAppointmentParams {

	return CreateAppointmentParams{}
}

// CreateAppointmentParams contains all the bound params for the create appointment operation
// typically these are obtained from a http.Request
//
// swagger:parameters createAppointment
type CreateAppointmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Appointment *models.UserAppointment
	/*Provided by API GW after auth
	  Required: true
	  In: header
	*/
	Userid strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateAppointmentParams() beforehand.
func (o *CreateAppointmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserAppointment
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("appointment", "body", ""))
			} else {
				res = append(res, errors.NewParseError("appointment", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Appointment = &body
			}
		}
	} else {
		res = append(res, errors.Required("appointment", "body", ""))
	}
	if err := o.bindUserid(r.Header[http.CanonicalHeaderKey("userid")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUserid binds and validates parameter Userid from header.
func (o *CreateAppointmentParams) bindUserid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("userid", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("userid", "header", raw); err != nil {
		return err
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("userid", "header", "strfmt.UUID", raw)
	}
	o.Userid = *(value.(*strfmt.UUID))

	if err := o.validateUserid(formats); err != nil {
		return err
	}

	return nil
}

// validateUserid carries on validations for parameter Userid
func (o *CreateAppointmentParams) validateUserid(formats strfmt.Registry) error {

	if err := validate.FormatOf("userid", "header", "uuid", o.Userid.String(), formats); err != nil {
		return err
	}
	return nil
}
