// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/AlexanderYukhanov/90minsGOexp/server/models"
)

// ListAvailableTimesForTrainerOKCode is the HTTP code returned for type ListAvailableTimesForTrainerOK
const ListAvailableTimesForTrainerOKCode int = 200

/*ListAvailableTimesForTrainerOK List of available time slots

swagger:response listAvailableTimesForTrainerOK
*/
type ListAvailableTimesForTrainerOK struct {

	/*
	  In: Body
	*/
	Payload models.AvailableSlots `json:"body,omitempty"`
}

// NewListAvailableTimesForTrainerOK creates ListAvailableTimesForTrainerOK with default headers values
func NewListAvailableTimesForTrainerOK() *ListAvailableTimesForTrainerOK {

	return &ListAvailableTimesForTrainerOK{}
}

// WithPayload adds the payload to the list available times for trainer o k response
func (o *ListAvailableTimesForTrainerOK) WithPayload(payload models.AvailableSlots) *ListAvailableTimesForTrainerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list available times for trainer o k response
func (o *ListAvailableTimesForTrainerOK) SetPayload(payload models.AvailableSlots) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAvailableTimesForTrainerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AvailableSlots{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListAvailableTimesForTrainerBadRequestCode is the HTTP code returned for type ListAvailableTimesForTrainerBadRequest
const ListAvailableTimesForTrainerBadRequestCode int = 400

/*ListAvailableTimesForTrainerBadRequest Bad request

swagger:response listAvailableTimesForTrainerBadRequest
*/
type ListAvailableTimesForTrainerBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListAvailableTimesForTrainerBadRequest creates ListAvailableTimesForTrainerBadRequest with default headers values
func NewListAvailableTimesForTrainerBadRequest() *ListAvailableTimesForTrainerBadRequest {

	return &ListAvailableTimesForTrainerBadRequest{}
}

// WithPayload adds the payload to the list available times for trainer bad request response
func (o *ListAvailableTimesForTrainerBadRequest) WithPayload(payload *models.Error) *ListAvailableTimesForTrainerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list available times for trainer bad request response
func (o *ListAvailableTimesForTrainerBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAvailableTimesForTrainerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListAvailableTimesForTrainerUnauthorizedCode is the HTTP code returned for type ListAvailableTimesForTrainerUnauthorized
const ListAvailableTimesForTrainerUnauthorizedCode int = 401

/*ListAvailableTimesForTrainerUnauthorized Unauthorized

swagger:response listAvailableTimesForTrainerUnauthorized
*/
type ListAvailableTimesForTrainerUnauthorized struct {
}

// NewListAvailableTimesForTrainerUnauthorized creates ListAvailableTimesForTrainerUnauthorized with default headers values
func NewListAvailableTimesForTrainerUnauthorized() *ListAvailableTimesForTrainerUnauthorized {

	return &ListAvailableTimesForTrainerUnauthorized{}
}

// WriteResponse to the client
func (o *ListAvailableTimesForTrainerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ListAvailableTimesForTrainerNotFoundCode is the HTTP code returned for type ListAvailableTimesForTrainerNotFound
const ListAvailableTimesForTrainerNotFoundCode int = 404

/*ListAvailableTimesForTrainerNotFound Trainer not found

swagger:response listAvailableTimesForTrainerNotFound
*/
type ListAvailableTimesForTrainerNotFound struct {
}

// NewListAvailableTimesForTrainerNotFound creates ListAvailableTimesForTrainerNotFound with default headers values
func NewListAvailableTimesForTrainerNotFound() *ListAvailableTimesForTrainerNotFound {

	return &ListAvailableTimesForTrainerNotFound{}
}

// WriteResponse to the client
func (o *ListAvailableTimesForTrainerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
