// Code generated by go-swagger; DO NOT EDIT.

// Package restapi An experimental server
//
//  An experimental server
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <a.yukhanov@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
