// Code generated by go-swagger; DO NOT EDIT.

package trainers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/AlexanderYukhanov/90minsGOexp/server/models"
)

// ListTrainerAppointmentsOKCode is the HTTP code returned for type ListTrainerAppointmentsOK
const ListTrainerAppointmentsOKCode int = 200

/*ListTrainerAppointmentsOK List of appointments

swagger:response listTrainerAppointmentsOK
*/
type ListTrainerAppointmentsOK struct {

	/*
	  In: Body
	*/
	Payload models.TrainerAppointments `json:"body,omitempty"`
}

// NewListTrainerAppointmentsOK creates ListTrainerAppointmentsOK with default headers values
func NewListTrainerAppointmentsOK() *ListTrainerAppointmentsOK {

	return &ListTrainerAppointmentsOK{}
}

// WithPayload adds the payload to the list trainer appointments o k response
func (o *ListTrainerAppointmentsOK) WithPayload(payload models.TrainerAppointments) *ListTrainerAppointmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list trainer appointments o k response
func (o *ListTrainerAppointmentsOK) SetPayload(payload models.TrainerAppointments) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTrainerAppointmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.TrainerAppointments{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListTrainerAppointmentsBadRequestCode is the HTTP code returned for type ListTrainerAppointmentsBadRequest
const ListTrainerAppointmentsBadRequestCode int = 400

/*ListTrainerAppointmentsBadRequest Bad Request

swagger:response listTrainerAppointmentsBadRequest
*/
type ListTrainerAppointmentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTrainerAppointmentsBadRequest creates ListTrainerAppointmentsBadRequest with default headers values
func NewListTrainerAppointmentsBadRequest() *ListTrainerAppointmentsBadRequest {

	return &ListTrainerAppointmentsBadRequest{}
}

// WithPayload adds the payload to the list trainer appointments bad request response
func (o *ListTrainerAppointmentsBadRequest) WithPayload(payload *models.Error) *ListTrainerAppointmentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list trainer appointments bad request response
func (o *ListTrainerAppointmentsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTrainerAppointmentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListTrainerAppointmentsUnauthorizedCode is the HTTP code returned for type ListTrainerAppointmentsUnauthorized
const ListTrainerAppointmentsUnauthorizedCode int = 401

/*ListTrainerAppointmentsUnauthorized Unauthorized

swagger:response listTrainerAppointmentsUnauthorized
*/
type ListTrainerAppointmentsUnauthorized struct {
}

// NewListTrainerAppointmentsUnauthorized creates ListTrainerAppointmentsUnauthorized with default headers values
func NewListTrainerAppointmentsUnauthorized() *ListTrainerAppointmentsUnauthorized {

	return &ListTrainerAppointmentsUnauthorized{}
}

// WriteResponse to the client
func (o *ListTrainerAppointmentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
